### ISSUE TITLE
High CPU usage when sitting idle

### ISSUE THREAD

**Issue by nguyer** [hyperledger-labs/firefly-tokens-erc1155#22]
When I use the firefly-cli to create a new stack, as soon as the stack comes up, before the user interacts with the system at all, the CPU usage of both firefly-tokens-erc1155 and firefly-ethconnect is very high. This causes my machine to run hot, loud, and slow. If I run the same stack without a token connector ethconnect idles at < 1% CPU usage, so I suspect it's some interaction caused by the token connector that is causing the spike.

```
CONTAINER ID   NAME                    CPU %     MEM USAGE / LIMIT     MEM %     NET I/O           BLOCK I/O         PIDS
961488d1f524   test_tokens_0_1         86.86%    52.25MiB / 15.54GiB   0.33%     216MB / 229MB     0B / 4.1kB        22
e9dba6fdd5ba   test_tokens_1_1         87.37%    53.53MiB / 15.54GiB   0.34%     215MB / 228MB     643kB / 4.1kB     22
2a9f77c7c4ee   test_ethconnect_0_1     78.51%    16.38MiB / 15.54GiB   0.10%     229MB / 216MB     0B / 12.3kB       15
678af5c8b919   test_ethconnect_1_1     77.72%    13.96MiB / 15.54GiB   0.09%     228MB / 215MB     0B / 12.3kB       14
```

**Comment by awrichar** [comment]
Seems to be caused by #14
